// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protos/service.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CMQ service

type CMQService interface {
	Push(ctx context.Context, in *CMQPushServiceReq, opts ...client.CallOption) (*CMQPushServiceResp, error)
}

type cMQService struct {
	c    client.Client
	name string
}

func NewCMQService(name string, c client.Client) CMQService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "service"
	}
	return &cMQService{
		c:    c,
		name: name,
	}
}

func (c *cMQService) Push(ctx context.Context, in *CMQPushServiceReq, opts ...client.CallOption) (*CMQPushServiceResp, error) {
	req := c.c.NewRequest(c.name, "CMQ.Push", in)
	out := new(CMQPushServiceResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CMQ service

type CMQHandler interface {
	Push(context.Context, *CMQPushServiceReq, *CMQPushServiceResp) error
}

func RegisterCMQHandler(s server.Server, hdlr CMQHandler, opts ...server.HandlerOption) error {
	type cMQ interface {
		Push(ctx context.Context, in *CMQPushServiceReq, out *CMQPushServiceResp) error
	}
	type CMQ struct {
		cMQ
	}
	h := &cMQHandler{hdlr}
	return s.Handle(s.NewHandler(&CMQ{h}, opts...))
}

type cMQHandler struct {
	CMQHandler
}

func (h *cMQHandler) Push(ctx context.Context, in *CMQPushServiceReq, out *CMQPushServiceResp) error {
	return h.CMQHandler.Push(ctx, in, out)
}
